### ISSUE TITLE
LoggerFactory.GetInstance does not return a new instance of the logger

### ISSUE THREAD

**Issue by killyosaur** [RockLib/RockLib.Logging#43]
From what I can see in your implementation, when I call for an instance of a logger for the first time, it creates that instance but subsequent calls are pulled from the dictionary. I do not see any checks that the instance is still valid and in an application with per scope/per instance dependency injection, that instance will get disposed of at the end of the call to it.

**Comment by keithelder** [comment]
It is a factory so it is supposed to only create the instance once per type/category creation if I remember correctly. Creating the logger is expensive and isn't supposed to be recreated with each and every call.

**Comment by killyosaur** [comment]
That's all fine and good, but that call doesn't check that the instance has been disposed of if/when someone does use DI as something other than Singleton.

**Comment by bfriesen** [comment]
Indeed it does not dispose of the logger instances in 1.x. We've addressed the issue in the [2.0 version](https://github.com/RockLib/RockLib.Logging/tree/2.0), which has pre-releases published to nuget right now (we anticipate publishing the release version next week). Instead of `LoggerFactory.GetInstance`, version 2.0 has two methods: `LoggerFactory.Create` and `LoggerFactory.GetCached`. This is exactly your suggestion. :)

**Comment by killyosaur** [comment]
that it is, thanks for the update!
